### ISSUE TITLE
Support for Intrinsic functions in 'value'

### ISSUE THREAD

**Issue by circulon** [mysense-ai/ServerlessPlugin-SSMPublish#145]
I like this plugin but have come accross an issue when using intrinsic functions and  the 'value' option.

The plugin only supports `string` or `object` as types for the 'value'option.
As such the following usage does not work.
```yaml
  ssmPublish:
    enabled: true # Needs to be set to true
    params:
      - path: ${self:custom.config.general.ssmResourcePathPrefix}/bucket/shared
        value: 
          Fn::GetAtt: S3AttachmentsBucket.Arn
```
This results in the raw text `Fn::GetAtt: S3AttachmentsBucket.Arn` being put in the SSM parameter and not the ARN od the resource as expected.

I know that this same thing can be achieved using the `source` option and adding the extra ref to the `Outputs` section.
This defeats the security of `secureString` when you have   passwords and other data that should have restricted access visible in plain text in the CF templates outputs for anyone to see.

I am not familiar with typeScript and am struggling to understand where / how to resolve the value as a CF template intrinsic function instead of a raw string?

From the looks of the code it would be fairly easy but I have no idea how to implement it and create a PR.

Pointers or code snippets are welcome but also if this is an easy fix it would be greatly appreciated if it could just be fixed.
