### ISSUE TITLE
optional SSM cleanup

### ISSUE THREAD

**Issue by ColdFire87** [mysense-ai/ServerlessPlugin-SSMPublish#33]
```yaml
ssmPublish:
    enabled: true
    cleanup:
      path: /service/config
    params:
      - path: /service/config/foo
        value: foo
      - path: /service/config/bar
        value: bar
```

1. Fetch all values under `cleanup.path`.
2. Run a difference against `params[].path`
3. Delete SSM params in the difference set
